### ISSUE TITLE
UI stuck at "Initializing..." when using PyInstaller 5.8.0

### ISSUE THREAD

**Issue by brentvollebregt** [brentvollebregt/auto-py-to-exe#364]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [ ] [Not Applicable] I have made sure my application/script runs before trying to package 

**Describe the bug**
When running auto-py-to-exe, the UI is stuck on the "Initializing..." spinner. 

See screenshot:

![image](https://user-images.githubusercontent.com/19944838/218295786-e0f88023-7d29-4999-a850-2c6292e099d1.png)

The console contains no errors but Chrome's DevTools has this error:

```
Uncaught (in promise) TypeError: o.choices.map is not a function
    at interface.js:182:23
    at Array.forEach (<anonymous>)
    at _createSubSectionInAdvanced (interface.js:102:13)
    at interface.js:378:9
    at Array.forEach (<anonymous>)
    at constructAdvancedSection (interface.js:377:22)
    at initialise.js:76:5
```

**To Reproduce**
Steps to reproduce the behavior (install dependencies, do this in the auto-py-to-exe UI):
1. Install auto-py-to-exe using pip
2. Validate PyInstaller 5.8.0 is installed (this was released 14hrs ago at the time of writing)
3. Run auto-py-to-exe

On #3, the error will appear

**Expected behavior**

The "Initializing..." spinner should disappear.

**Your Environment:**
- Python version (`python --version`): 3.9.9
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.29.0
- PyInstaller version (`pip show pyinstaller`): 5.8.0
- Eel version (`pip show eel`): 0.14.0

**Comment by brentvollebregt** [comment]
It appears the choices passed from PyInstaller are no longer an array and is now a dictionary. A `.map` in JavaScript will no longer iterate over the values.

![image](https://user-images.githubusercontent.com/19944838/218295969-9ec2f59d-ba82-4105-844f-2105156a15a2.png)

This has been caused from this PR: https://github.com/pyinstaller/pyinstaller/pull/7414/files

**Comment by brentvollebregt** [comment]
Fixed in v2.29.1 (0917de365526304a6f2309b0d23fe63e05f089bd)

**Comment by victorhramos-dev** [comment]
not fixed, still happening
auto-py-to-exe: v.2.30.0
pyinstaller: 5.8.0
python: 3.7.9

**Comment by brentvollebregt** [comment]
@victorhramos-dev are you still getting the **exact** same issue? Please take a screenshot of the error in DevTools and paste it here.

**Comment by TalkLounge** [comment]
Can confirm, still happening

* Master Branch
* Python 3.10.5
* Windows 10 Home

![grafik](https://user-images.githubusercontent.com/26689633/221003281-297674cd-4026-4bfd-b449-982e5d446038.png)

**Comment by brentvollebregt** [comment]
@TalkLounge the call `o.choices.map` doesn't exist on the current master branch - [this commit removed it](https://github.com/brentvollebregt/auto-py-to-exe/commit/0917de365526304a6f2309b0d23fe63e05f089bd).

When you execute `auto-py-to-exe --version`, what do you get back?

**Comment by TalkLounge** [comment]
Seemed to be an cache issue. Reinstalling python fixed it for me

**Comment by AnonymousCoderArtist** [comment]
![image](https://github.com/user-attachments/assets/e8a9f04b-1dc4-4e6e-9aa5-0b9e92648a31)
Getting the same error again

**Comment by brentvollebregt** [comment]
@AnonymousCoderArtist, from what I can see, this is not happening on the latest auto-py-to-exe and pyinstaller. Please check you are using the latest versions.

If this is still happening on the latest versions for you, please create a new issue and list the versions you are using in the issue template.

**Comment by AnonymousCoderArtist** [comment]
ok
